name = "LemmaGeneralis"
version = "0.1.0"

[leanOptions]
autoImplicit = false

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "main"

[[require]]
name = "Aesop"
scope = "leanprover-community"

[[lean_lib]]
name = "LemmaGeneralis"
